mode: deployment
config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

  processors:
    batch: {}
    filter:
      spans:
        exclude:
          match_type: strict
          span_names:
            - /metrics

  exporters:
    otlp:
      endpoint: http://tempo.grafana.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    telemetry:
      logs:
        level: "debug"
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch, filter]
        exporters: [otlp]